server:
  port: 8081

camel:
  servlet:
    mapping:
      context-path: /services/*

spring:
  h2:
    console:
      enabled: true
  datasource:
    name: h2
    url: jdbc:h2:mem:sanjay

com.camel:
  seda:
    enabled: false
  error-handlers:
    enabled: false
  error-handlers1:
    enabled: false
  aggregator:
    enabled: false
